# Generated by Django 4.2.3 on 2023-07-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherNow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muni_code', models.CharField(max_length=100)),
                ('muni_name', models.CharField(max_length=100)),
                ('prov_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muni_prov_code', to='weatherNow.provincia')),
            ],
        ),
    ]
