# Generated by Django 4.2.3 on 2023-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherNow', '0002_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='muni_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='prov_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
